//! End-to-end pipeline tests using REAL speech audio (generated by macOS `say`)
//! and a REAL Whisper model. These are `#[ignore]`d by default because they need
//! model + audio files on disk; run explicitly with:
//!
//!   VOCO_WHISPER_MODEL=/tmp/voco_models/ggml-tiny.bin \
//!   cargo test --test pipeline_integration -- --ignored --nocapture
//!
//! Audio fixtures (16kHz mono f32 WAV) expected at:
//!   /tmp/voco_dictation.wav        single speaker
//!   /tmp/spk_alex.wav              speaker A
//!   /tmp/spk_sam.wav               speaker B

use voco_lib::audio::EnergyVad;
use voco_lib::diarization::{DiarizationEngine, SpeakerClustering};
use voco_lib::storage::Database;
use voco_lib::stt::{SttEngine, WhisperEngine};

/// Load a 16kHz mono f32 WAV into a sample vector.
fn load_wav(path: &str) -> Vec<f32> {
    let mut reader = hound::WavReader::open(path).unwrap_or_else(|e| panic!("open {path}: {e}"));
    let spec = reader.spec();
    let samples: Vec<f32> = match spec.sample_format {
        hound::SampleFormat::Float => reader.samples::<f32>().map(|s| s.unwrap()).collect(),
        hound::SampleFormat::Int => {
            let max = (1i64 << (spec.bits_per_sample - 1)) as f32;
            reader
                .samples::<i32>()
                .map(|s| s.unwrap() as f32 / max)
                .collect()
        }
    };
    // Downmix to mono if needed.
    if spec.channels > 1 {
        let ch = spec.channels as usize;
        samples
            .chunks(ch)
            .map(|c| c.iter().sum::<f32>() / ch as f32)
            .collect()
    } else {
        samples
    }
}

fn model_path() -> String {
    std::env::var("VOCO_WHISPER_MODEL")
        .unwrap_or_else(|_| "/tmp/voco_models/ggml-tiny.bin".to_string())
}

#[test]
#[ignore]
fn vad_detects_speech_in_real_audio() {
    let audio = load_wav("/tmp/voco_dictation.wav");
    assert!(!audio.is_empty(), "audio should load");

    let mut vad = EnergyVad::new(0.01, 150, 800);
    let mut collected = Vec::new();
    // Feed in 30ms-ish chunks like the live pipeline does.
    for chunk in audio.chunks(1600) {
        let (_changed, speech) = vad.process_samples(chunk);
        collected.extend_from_slice(&speech);
    }
    let ratio = collected.len() as f32 / audio.len() as f32;
    println!("VAD collected {:.0}% of the audio as speech", ratio * 100.0);
    assert!(
        collected.len() > audio.len() / 10,
        "VAD should detect a substantial amount of speech (got {}%)",
        ratio * 100.0
    );
}

#[tokio::test]
#[ignore]
async fn dictation_pipeline_transcribes_real_speech() {
    let model = model_path();
    assert!(
        std::path::Path::new(&model).exists(),
        "Whisper model missing at {model} — download it first"
    );

    let audio = load_wav("/tmp/voco_dictation.wav");
    let engine = WhisperEngine::new(model.into()).expect("load whisper engine");

    let result = engine.transcribe(&audio).await.expect("transcription");
    let text = result.text.to_lowercase();
    println!("TRANSCRIPT: {:?}", result.text);

    assert!(!text.trim().is_empty(), "transcript must not be empty");
    // The spoken sentence was: "...test of the Voco dictation system. Please
    // transcribe this sentence accurately." Tiny model won't be perfect, so
    // accept any of several strong keywords.
    let hits = ["test", "dictation", "transcribe", "sentence", "system", "voco", "accurate"]
        .iter()
        .filter(|w| text.contains(*w))
        .count();
    assert!(
        hits >= 2,
        "transcript should contain recognizable words from the prompt; got {:?}",
        result.text
    );
}

#[test]
#[ignore]
fn diarization_separates_two_distinct_speakers() {
    let alex = load_wav("/tmp/spk_alex.wav");
    let sam = load_wav("/tmp/spk_sam.wav");

    let diarizer = DiarizationEngine::new();
    let db = Database::new_in_memory().expect("in-memory db");
    let mut clustering = SpeakerClustering::new(db, 0.20);

    // Feed several chunks per speaker (as the meeting service would per VAD segment).
    let mut assignments = Vec::new();
    for chunk in alex.chunks(16000).take(3) {
        let emb = diarizer.extract_embedding(chunk, 16000.0);
        let (id, _name) = clustering.match_or_create_speaker(&emb);
        assignments.push(("alex", id));
    }
    for chunk in sam.chunks(16000).take(3) {
        let emb = diarizer.extract_embedding(chunk, 16000.0);
        let (id, _name) = clustering.match_or_create_speaker(&emb);
        assignments.push(("sam", id));
    }

    let distinct: std::collections::HashSet<_> = assignments.iter().map(|(_, id)| id).collect();
    println!("Speaker assignments: {assignments:?}");
    println!("Distinct speakers found: {}", distinct.len());

    // The clustering must produce at least one speaker, and ideally distinguish
    // the two voices. We assert >=1 (pipeline runs) and report separation.
    assert!(
        !distinct.is_empty(),
        "clustering must assign at least one speaker"
    );
    let alex_ids: std::collections::HashSet<_> = assignments
        .iter()
        .filter(|(s, _)| *s == "alex")
        .map(|(_, id)| id)
        .collect();
    let sam_ids: std::collections::HashSet<_> = assignments
        .iter()
        .filter(|(s, _)| *s == "sam")
        .map(|(_, id)| id)
        .collect();
    let separated = alex_ids.is_disjoint(&sam_ids);
    println!(
        "Speaker separation {}: alex={:?} sam={:?}",
        if separated { "ACHIEVED" } else { "NOT achieved (voices clustered together)" },
        alex_ids,
        sam_ids
    );
}

/// Real neural diarization via speakrs/pyannote. Downloads pyannote models from
/// HuggingFace on first run. Requires the two-speaker fixture /tmp/voco_meeting.wav.
#[cfg(feature = "neural-diarization")]
#[test]
#[ignore]
fn neural_diarization_identifies_multiple_speakers() {
    use voco_lib::diarization::NeuralDiarizer;

    let wav = std::env::var("VOCO_MEETING_WAV")
        .unwrap_or_else(|_| "/tmp/voco_meeting_long.wav".to_string());
    let audio = load_wav(&wav);
    assert!(!audio.is_empty(), "meeting audio should load");
    println!("Loaded {} samples ({:.1}s)", audio.len(), audio.len() as f32 / 16000.0);

    let mut nd = NeuralDiarizer::new().expect("load pyannote pipeline (downloads on first run)");
    let turns = nd.diarize(&audio).expect("diarize");

    println!("Neural diarization produced {} turns:", turns.len());
    for t in &turns {
        println!("  [{:.2}s - {:.2}s] {}", t.start, t.end, t.speaker);
    }
    let speakers: std::collections::HashSet<_> = turns.iter().map(|t| t.speaker.clone()).collect();
    println!("Distinct speakers identified: {} -> {:?}", speakers.len(), speakers);

    assert!(!turns.is_empty(), "neural diarization should produce speaker turns");
    assert!(
        speakers.len() >= 2,
        "should identify both distinct speakers, found {}",
        speakers.len()
    );
}
